/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.model.TimestampType;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * UserObjectUsage
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2024-02-19T21:28:12.651360Z[Europe/Dublin]")
public class UserObjectUsage   {
  @JsonProperty("allocatedAmount")
  private Long allocatedAmount = null;

  @JsonProperty("sessionId")
  private Long sessionId = null;

  @JsonProperty("lastSeen")
  private TimestampType lastSeen = null;

  public UserObjectUsage allocatedAmount(Long allocatedAmount) {
    this.allocatedAmount = allocatedAmount;
    return this;
  }

  /**
   * Get allocatedAmount
   * @return allocatedAmount
   **/
  @JsonProperty("allocatedAmount")
  @Schema(description = "")
  public Long getAllocatedAmount() {
    return allocatedAmount;
  }

  public void setAllocatedAmount(Long allocatedAmount) {
    this.allocatedAmount = allocatedAmount;
  }

  public UserObjectUsage sessionId(Long sessionId) {
    this.sessionId = sessionId;
    return this;
  }

  /**
   * Get sessionId
   * @return sessionId
   **/
  @JsonProperty("sessionId")
  @Schema(description = "")
  public Long getSessionId() {
    return sessionId;
  }

  public void setSessionId(Long sessionId) {
    this.sessionId = sessionId;
  }

  public UserObjectUsage lastSeen(TimestampType lastSeen) {
    this.lastSeen = lastSeen;
    return this;
  }

  /**
   * Get lastSeen
   * @return lastSeen
   **/
  @JsonProperty("lastSeen")
  @Schema(description = "")
  @Valid
  public TimestampType getLastSeen() {
    return lastSeen;
  }

  public void setLastSeen(TimestampType lastSeen) {
    this.lastSeen = lastSeen;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserObjectUsage userObjectUsage = (UserObjectUsage) o;
    return Objects.equals(this.allocatedAmount, userObjectUsage.allocatedAmount) &&
        Objects.equals(this.sessionId, userObjectUsage.sessionId) &&
        Objects.equals(this.lastSeen, userObjectUsage.lastSeen);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allocatedAmount, sessionId, lastSeen);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserObjectUsage {\n");
    
    sb.append("    allocatedAmount: ").append(toIndentedString(allocatedAmount)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    lastSeen: ").append(toIndentedString(lastSeen)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
